import type { Metadata } from "next";
import "./globals.css";

import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { Header } from "@/components/header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"min-h-[100dvh] bg-background font-sans antialiased",
					fontSans.variable,
				)}
			>
				<Header />
				{children}
			</body>
		</html>
	);
}
